module interoperability {
	module test {
        struct Inner {
            uint8 a;
            uint32 b;
            uint16 c;
        };

        struct Nested {
            Inner inner;
            int64 level;
            int32 other;
            sequence <int64, 100> value_list;
            Inner inner_array[10];
            float float_array[5];

            int32 last;
        };
    };
};